name: Android Release Build

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant permission to gradlew
        run: chmod +x gradlew

      - name: Decode Keystore
        # متن Base64 را به فایل فیزیکی با نام ipcloud.jks تبدیل می‌کند
        run: echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > ipcloud.jks

      - name: Build Signed APK
        # از آدرس مستقیم استفاده می‌کنیم تا سیستم بیلد فایل را دقیق پیدا کند
        run: |
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=$(pwd)/ipcloud.jks \
            -Pandroid.injected.signing.store.password=${{ secrets.KEY_STORE_PASSWORD }} \
            -Pandroid.injected.signing.key.alias=${{ secrets.ALIAS }} \
            -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: IP-Cloud-Signed-APK
          path: app/build/outputs/apk/release/*.apk