name: Android Release Build

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    # Ø§ÛŒÙ† Ø®Ø· Ø§Ø¬Ø§Ø²Ù‡ Ø³Ø§Ø®Øª Release Ø±Ø§ Ø¨Ù‡ Ø§Ú©Ø´Ù† Ù…ÛŒâ€ŒØ¯Ù‡Ø¯
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant permission to gradlew
        run: chmod +x gradlew

      - name: Decode Keystore
        run: echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > ipcloud.jks

      - name: Build Signed APK
        run: |
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=$(pwd)/ipcloud.jks \
            -Pandroid.injected.signing.store.password=${{ secrets.KEY_STORE_PASSWORD }} \
            -Pandroid.injected.signing.key.alias=${{ secrets.ALIAS }} \
            -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

      - name: Rename APK
        # ØªØºÛŒÛŒØ± Ù†Ø§Ù… ÙØ§ÛŒÙ„ Ø¨Ù‡ Ø§Ø³Ù… Ø¯Ù„Ø®ÙˆØ§Ù‡ Ø´Ù…Ø§
        run: mv app/build/outputs/apk/release/*.apk app/build/outputs/apk/release/IP-Cloud-V1.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/release/IP-Cloud-V1.apk
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          body: |
            ğŸš€ Ù†Ø³Ø®Ù‡ Ø¬Ø¯ÛŒØ¯ Ø§Ù¾Ù„ÛŒÚ©ÛŒØ´Ù† Ø¢Ù…Ø§Ø¯Ù‡ Ø´Ø¯!
            
            âœ¨ ØªØºÛŒÛŒØ±Ø§Øª:
            - Ø¨Ù‡Ø¨ÙˆØ¯ Ø¹Ù…Ù„Ú©Ø±Ø¯ Ùˆ Ø±ÙØ¹ Ø¨Ø§Ú¯â€ŒÙ‡Ø§
            - Ø¨ÛŒÙ„Ø¯ Ø®ÙˆØ¯Ú©Ø§Ø± ØªÙˆØ³Ø· GitHub Actions
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}